### ISSUE TITLE
Rename ribbon from "iCubTech" to creo2urdf ? 

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/creo2urdf#101]
While working with @DavideBarbone, I realized it is a bit confusing for non-IIT users for creo2urdf to understand why they need to navigate to the "iCubTech" ribbon to actually find the "creo2urdf" button. Could it make sense to rename the "iCubTech" ribbon to creo2urdf ?

**Comment by Nicogene** [comment]
You are right, maybe it is better to place it in the `Tools` ribbon as the `Mathworks` one

**Comment by mfussi66** [comment]
I created a new ribbon file that addresses the issue. However, it seems impossible to "inject" the creo2urdf button in the Mathworks group, so I did the following:

![immagine](https://github.com/user-attachments/assets/19b510dd-5560-4102-a3ca-b4ba507b148a)

Let me know if it's ok.

The validation button can be removed as it's not used at the moment.

**Comment by traversaro** [comment]
I like it! The only minor comment is that URDF is an acronym, so in general it does not make a lot of sense to capitalize it, so I would either write URDF or urdf, while Urdf looks a bit strange (see for example how UDF Library is capitalized in the Utilities Menu).

**Comment by mfussi66** [comment]
Coming right up:

![immagine](https://github.com/user-attachments/assets/f598b18b-47c3-4afe-ae86-107b4bc8cd69)

**Comment by Nicogene** [comment]
Fixed by #108
