### ISSUE TITLE
Remove "Validate" button?

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/creo2urdf#102]
Working with @davidebarbone, I noticed it was a bit confusing to have a "Validate" button that does not work. If we are not using the button at the moment, could it make sense to just remove it?

**Comment by Nicogene** [comment]
This was a button that worked for simple assemblies but the validation joint per joint is not feasible for complex assemblies, and for the time being we decided just to "disconnect" it, but if its presence is confusing we can remove it from the ribbon it should be trivial

**Comment by traversaro** [comment]
What is the advantage of "disconnecting" it as opposed to just remove it?

**Comment by Nicogene** [comment]
> What is the advantage of "disconnecting" it as opposed to just remove it? At least from the GUI, then the code can still be there, but at least it does not confuse new users.

Totally agree, it has probably been done to remove it quickly

**Comment by Nicogene** [comment]
Fixed by #108
