### ISSUE TITLE
Missing installation of YCM? 

### ISSUE THREAD

**Issue by traversaro** [icub-tech-iit/creo2urdf#22]
I noticed that in the README there is no mention of how to install YCM, but then in the CMakeLists.txt YCM is required. Probably we should either write how to install YCM, or just use it via FetchContent ?

**Comment by Nicogene** [comment]
Since we use ycm only for the `uninstall` target, and this plugin does not need to be installed in order to be used, we decided for now to remove this dependency, see https://github.com/icub-tech-iit/creo2urdf/pull/25.
