### ISSUE TITLE
CREO2URDF – Write up documentation of classes

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/creo2urdf#58]
We might add the documentation of the classes using doxygen and deploy it in a dedicated website

**Comment by mfussi66** [comment]
I started this activity in the branch https://github.com/icub-tech-iit/creo2urdf/tree/doxygen , actually starting off from `Utils.h`, so that everything can be covered.

**Comment by mfussi66** [comment]
I completed the documentation of the files, and added a Doxyfile to the branch. Additionally, I started setting up the github action, but first I need to study how it works.

**Comment by Nicogene** [comment]
> I completed the documentation of the files, and added a Doxyfile to the branch. Additionally, I started setting up the github action, but first I need to study how it works.

You can take inspiration from
- ergocub-software: https://github.com/icub-tech-iit/ergocub-software/blob/master/.github/workflows/gh-pages.yml
- robometry: https://github.com/robotology/robometry/blob/master/.github/workflows/gh-pages.yml

They do the same thing with two different approaches

**Comment by Nicogene** [comment]
We are online:
- https://icub-tech-iit.github.io/creo2urdf/
